"""
SecureVault - Password Security Audit Tool

Author: Harsha BV
Description:
SecureVault analyzes password strength, detects reused passwords,
and generates a security risk report to help identify weak credentials.

Use Case:
Simulates how security teams audit leaked or user-entered passwords
to prevent account compromise.
"""

import re
from collections import Counter

def password_strength(password):
    score = 0
    if len(password) >= 8:
        score += 1
    if re.search(r"[A-Z]", password):
        score += 1
    if re.search(r"[a-z]", password):
        score += 1
    if re.search(r"[0-9]", password):
        score += 1
    if re.search(r"[!@#$%^&*]", password):
        score += 1
    return score

def analyze_passwords():
    with open("passwords.txt", "r") as file:
        passwords = [line.strip() for line in file]

    reused = [pwd for pwd, count in Counter(passwords).items() if count > 1]

    report = []
    report.append("SECUREVAULT SECURITY REPORT\nGenerated by SecureVault\n\n")
    report.append("------------------------------\n")

    for pwd in passwords:
        strength = password_strength(pwd)
        if strength <= 2:
            risk = "HIGH RISK"
        elif strength <= 4:
            risk = "MEDIUM RISK"
        else:
            risk = "LOW RISK"

        report.append(f"Password: {pwd} | Score: {strength}/5 | Risk: {risk}\n")

    if reused:
        report.append("\nReused Passwords Detected:\n")
        for r in reused:
            report.append(f"- {r}\n")

    with open("report.txt", "w") as file:
        file.writelines(report)

    print("Security analysis complete. Report generated.")

analyze_passwords()
